### ISSUE TITLE
Error: Unbound value `String.to_seq`

### ISSUE THREAD

**Issue by slondr** [mk270/gemtext2md#1]
When I try to run the program via ocaml or compile it via ocamlc, I get the titular error reported on line 144, charactesr 4-17 and nothing else.

I am using OCaml 4.06.1; is that too old or new for gemtext2md?

**Comment by mk270** [comment]
thanks for your interest!

I am using OCaml 4.14.0 - so it may be that your version of ocaml is not recent enough, but that does seem surprising. Can you use *any* of the functions in String?

**Comment by slondr** [comment]
https://v2.ocaml.org/api/String.html <-- this page seems to imply that String.to_seq was added in 4.07, older than your version but newer than mine. So that's definitely the problem. Thanks for the hint!
